starburstdata/dbt-trino

README.md, docker-compose.yml, docker/Dockerfile.util, docker/trino/etc/jvm.config, docker/wait_for_up.bash
Commit: https://github.com/findinpath/dbt-trino/commit/e5f1096d902592640a1e048265870f1e1d056b4d introduces changes which caused docker image to fail during building.
There is a small commit which adds recommended flag for JVM config.
=> Update docker image

README.md, dbt/include/trino/macros/adapters.sql
Addresses: https://github.com/starburstdata/dbt-trino/issues/16
=> Change default batch size to 1000

dbt/adapters/trino/connections.py
dbt-trino adapter uses connection in auto-commit mode, hence there is no need to separately start a new transaction in each query since it makes no effect. In auto-commit mode, the client will create a new transaction for each query. 
That would resolve timeout issue reported here: https://github.com/starburstdata/dbt-trino/issues/20
=> Drop transaction queries

CHANGELOG.md, README.md, docker-compose-starburst.yml, docker-compose-trino.yml, docker/init_starburst.bash, docker/init_trino.bash, docker/starburst/catalog/postgresql.properties, docker/trino/catalog/postgresql.properties
- Description: Add PostgreSQL docker container for testing to test advanced features. Memory catalog cannot be completely replaced since views are not supported in PostgreSQL connector.
- Related issue(s): https://github.com/starburstdata/dbt-trino/issues/66
- Related code pull request(s): https://github.com/starburstdata/dbt-trino/pull/60
=> Add PostgreSQL docker container for testing

CHANGELOG.md, README.md, dbt/adapters/trino/connections.py, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/materializations/seeds/helpers.sql, dev_requirements.txt, tests/conftest.py, tests/functional/adapter/materialization/test_prepared_statements.py, tests/unit/test_adapter.py
Remove prepared statements emulation from dbt-trino and rely on the prepared statements support of native python types from trino-python-client
- Description:
- Related link(s): [Improved python types from trino-python-client](https://github.com/trinodb/trino-python-client#improved-python-types), #28
=> Use native prepared statements from trino-python-client

CHANGELOG.md, README.md, dbt/adapters/trino/connections.py
This PR fixes TrinoKerberosCredentials.trino_auth() in connections.py to include config, principal, and keytab necessary for kerberos authentication (tested with actual credentials).
=> Fix kerberos authentication

.github/workflows/security.yml
quick: true seems to generate following error `SCA Output file was not found - cannot proceed with creating issues. Please check prior execution errors.`
=> Fix veracode scanning

.changes/unreleased/Features-20220816-132608.yaml, README.md, dbt/include/trino/macros/materializations/incremental.sql, docker/starburst/catalog/iceberg.properties, tests/functional/adapter/materialization/test_incremental_delete_insert.py
- Description: Support multiple dbt native incremental strategies (delete+insert, merge (currently deactivated))
=> Add `delete+insert` materialization

.changes/unreleased/Features-20220816-180652.yaml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/catalog.sql, dbt/include/trino/macros/materializations/incremental.sql, dbt/include/trino/macros/materializations/table.sql, dbt/include/trino/macros/materializations/view.sql, tests/functional/adapter/persist_docs/fixtures.py, tests/functional/adapter/persist_docs/test_persist_docs.py, tests/functional/adapter/test_basic.py
- Description: Support for persist_docs
- Related issue(s): https://github.com/starburstdata/dbt-trino/issues/76
- Related code pull request(s): https://github.com/starburstdata/dbt-trino/pull/70 is needed to test the functionality since memory connector doesn't support comments. 
=> Support for persist_docs

.github/workflows/version-bump.yml
Support releasing without prerelease.
=> Support release without prerelease

.github/ISSUE_TEMPLATE/config.yml, README.md
Updated Slack channel links in order to correctly direct newbie users to the `#db-presto-trino` dbt Slack channel.
=> Update Slack channel links

setup.py
Just as dbt1.3 we required pyyaml 6.0, however seems that this version is not (yet) compatible with awscli. As pyyaml 5.4 is the first non-beta version to resolve the security issue, it is a safer candidate.
See https://github.com/starburstdata/dbt-trino/pull/106#issuecomment-1229173897
=> Require pyyaml 5.4 instead of 6.0

.changie.yaml, .github/workflows/bot-changelog.yml
Make specyfing issue number optional in changie
=> Make specyfing issue number optional in changie

.changes/unreleased/Features-20220922-085214.yaml, README.md, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/materializations/incremental.sql, tests/functional/adapter/materialization/fixtures.py, tests/functional/adapter/materialization/test_incremental_schema.py
=> Support `on_schema_change` for incremental models

.github/workflows/ci.yml
Skip running Galaxy tests on PRs from forks
=> Skip running Galaxy tests on PRs from forks

.changes/unreleased/Under the Hood-20221004-105758.yaml, dbt/adapters/trino/connections.py, dbt/adapters/trino/impl.py, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/crossdb/split_part.sql, tests/unit/test_adapter.py
get_columns_in_relation also accepts string parameters instead of `Relation` instances. These won't have `information_schema` property and therefore these queries will fail.
Improved exception handling
added macro `split_part`
=> `dbt_utils` upgrade related improvements

.changes/unreleased/Fixes-20221009-132438.yaml, dbt/adapters/trino/connections.py, tests/unit/test_adapter.py
resolves https://github.com/starburstdata/dbt-trino/issues/149 To work with certificate authentication in [`trino-python-client`](https://github.com/trinodb/trino-python-client)
Not updating any functionality or function signatures, so the README should not need an update.
=> Fixes instantiation of CertificateAuthentication object from trino-python-client

.changes/unreleased/Fixes-20221025-165844.yaml, dbt/include/trino/macros/materializations/incremental.sql, tests/functional/adapter/test_basic.py
Fix issue with `--full-refresh` on incremental models and added explicit test.
=> Fix table not dropped on incremental full refresh

.github/workflows/bot-changelog.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/version-bump.yml
Remove deprecated `set-output` and bump action version to get rid of deprecated node.js 12.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Workflows maintenance 

README.md, tests/unit/test_adapter.py
Change default value of query_max_run_time
=> Change default value of query_max_run_time

.changes/unreleased/Fixes-20221209-114403.yaml, dbt/adapters/trino/column.py, tests/unit/test_adapter.py
This is related to #35, the linked issue listed two separate issues, and one was already resolved.
>one is with dbt core: the varying(256) is hardcoded in dbt core and doesn't use the overriden TrinoColumn class methods. see [CT-78] [Bug] Adapters should be able to override string and numeric type of columns dbt-labs/dbt-core#4603 (PR submitted)
Now that the dbt-core PR has been merged, we can use the `TrinoColumn` class to handle the hard-coded `256`, the super class implementation still checks if `char_size is None` and sets it to `256` if is it `None.
https://github.com/dbt-labs/dbt-core/blob/0544b085439b3a635b8ce56adbf56d8e7c7e6839/core/dbt/adapters/base/column.py#L86-L94
In [dbt_utils.union_relations](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/union.sql) it uses the …
=> fix: correctly handle unbound varchar case instead of defaulting to varchar(256)

Makefile, dbt/adapters/trino/connections.py, setup.py, tests/functional/adapter/materialization/test_prepared_statements.py
- Add version in 'source' connection parameter
- Fix CI
- Disable prepared_statement tests on Galaxy
- Unpin trino-python-client version
=> 1.1.backport fixes

Makefile, dbt/adapters/trino/connections.py, setup.py, tests/functional/adapter/materialization/test_prepared_statements.py
- Add version in 'source' connection parameter
- Fix CI
- Disable prepared_statement tests on Galaxy
- Unpin trino-python-client version
=> 1.2.backport fixes

Makefile, dbt/adapters/trino/connections.py, docker-compose-starburst.yml, docker-compose-trino.yml, docker/starburst/catalog/delta.properties, setup.py, tests/functional/adapter/materialization/test_prepared_statements.py
- Add version in 'source' connection parameter
- Fix CI
- Disable prepared_statement tests on Galaxy
- Bump Trino and SEP versions in docker-compose files
- Unpin trino-python-client version
=> 1.3.backport fixes

.changes/unreleased/Features-20230308-200949.yaml, dbt/adapters/trino/connections.py, setup.py
=> Add query, query_id and rows_affected in adapter response

.changes/unreleased/Features-20230307-103324.yaml, README.md, dbt/include/trino/macros/materializations/materialized_view.sql, tests/functional/adapter/materialization/test_materialized_view.py
Add materialized view materialization
=> Add materialized view materialization

.changes/unreleased/Fixes-20230322-140501.yaml, dbt/include/trino/macros/catalog.sql
Fixes issue #272.
This PR rewrites the `trino__get_catalog` macro so that instead of using
```sql
select ... from system.metadata.table_comments where ... and schema_name in ('schema_1', 'schema_2', etc)
```
it uses `UNION ALL` to join subqueries which filter on one schema each, as follows:
```
select ... from system.metadata.table_comments where ... and schema_name = 'schema_1'
union all
select ... from system.metadata.table_comments where ... and schema_name = 'schema_2'
union all
etc.
```
By doing this, Trino reads only the table comments from the tables in the selected schemas instead of reading table comments from all tables in the catalog, which can be very slow.
With this change, running `dbt docs generate` is much faster, taking only a few seconds if the dbt project only contains …
=> Fix issue #272

.changes/unreleased/Dependencies-20230406-155907.yaml, .changes/unreleased/Dependencies-20230406-160125.yaml, .changes/unreleased/Dependencies-20230406-160407.yaml, .changes/unreleased/Dependencies-20230406-160756.yaml, .changes/unreleased/Dependencies-20230407-110511.yaml, .flake8, .pre-commit-config.yaml, dbt/adapters/trino/connections.py, dev_requirements.txt, tests/functional/adapter/test_session_property.py, tox.ini
1. Bumped versions of black, flake8, tox, with necessary other files adjustments.
2. Cleaned up `dev_requirements.txt`
- removed not used packages,
- removed packages which are used by pre-commit, as pre-commit creates its own environment for it hooks, 
- added compatibility pin for every package
=> Bump dependencies versions

.changes/unreleased/Features-20230419-115208.yaml, dbt/adapters/trino/__version__.py, dbt/adapters/trino/connections.py, dbt/adapters/trino/impl.py, dbt/include/trino/macros/adapters.sql, dev_requirements.txt, tests/functional/adapter/constraints/fixtures.py, tests/functional/adapter/constraints/test_constraints.py, tests/unit/utils.py
This PR is about:
1. Bumping dbt-core version to 1.5.0rc1
2. Implementing [model contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts) (new functionality in v1.5.)
(High level explanation of these changes in [this discussion](https://github.com/dbt-labs/dbt-core/discussions/7213) under `Model Contracts` section)
Some remarks about model contracts implementation:
1. It is implemented by running 2 queries: `Create table` and `Insert into` (similar as in dbt-redshift - [example query](https://github.com/dbt-labs/dbt-redshift/blob/v1.5.0rc1/tests/functional/adapter/test_constraints.py#L13-L33)).
It couldn't be implemeted as single CTAS query (as in dbt-snowflake - [example query](https://github.com/dbt-labs/dbt-snowflake/blob/v1.5.0rc1/tests/functional/adapter/test_constr …
=> Bumping version to 1.5.0rc2, Add model contracts

.changes/unreleased/Under the Hood-20230424-163631.yaml, .changes/unreleased/Under the Hood-20230424-163815.yaml, dbt/adapters/trino/column.py, tests/functional/adapter/column_types/fixtures.py, tests/functional/adapter/column_types/test_column_types.py, tests/functional/adapter/hooks/data/seed_model.sql, tests/functional/adapter/hooks/data/seed_run.sql, tests/functional/adapter/hooks/test_model_hooks.py, tests/functional/adapter/hooks/test_run_hooks.py, tests/functional/adapter/persist_docs/test_persist_docs.py, tests/functional/adapter/test_caching.py, tests/functional/adapter/test_simple_copy.py, tests/functional/adapter/test_simple_snapshot.py
Part of https://github.com/starburstdata/dbt-trino/issues/284
1. Added new tests from `dbt-tests-adapter` 1.5
2. Added Trino '_shims_' for methods `is_string`, `is_float`, `is_integer`, `is_numeric`
=> Add new tests from dbt-tests-adapter 1.5

.changes/unreleased/Dependencies-20230630-104322.yaml, setup.py
https://github.com/trinodb/trino-python-client/blob/master/CHANGES.md
=> Bump Trino to 0.326

.changes/unreleased/Under the Hood-20230630-122950.yaml, dbt/include/trino/macros/adapters.sql
This avoids a schema change in Iceberg when dbt does an:
```sql
comment on table sandbox.dbt_trino.rides is 'Combined table of NYC Taxi rides with the locations'
```
Because the comment is already there.
=> Set the table comment when creating the table

tests/functional/adapter/persist_docs/test_persist_docs.py
resolves #296 
Enabled TestPersistDocs tests on Galaxy, as it seems to be corrected on Galaxy side.
=> Enable TestPersistDocs tests on Galaxy

.changes/unreleased/Breaking Changes-20230721-125806.yaml, .changes/unreleased/Breaking Changes-20230724-140221.yaml, dbt/adapters/trino/__version__.py, dbt/adapters/trino/connections.py, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/materializations/materialized_view.sql, dev_requirements.txt, tests/functional/adapter/hooks/data/seed_model.sql, tests/functional/adapter/hooks/data/seed_run.sql, tests/functional/adapter/materialization/test_materialized_view.py, tests/functional/adapter/test_query_comments.py
- Update dbt-core and dbt-tests-adapter version to 1.6.0rc1
- Remove 'execute' method from TrinoConnectionManager, as implementation in SQLConnectionManager is sufficient, and new parameter was added there
- Remove redundant addition of query comments in 'add_query' method, as it is handled in 'execute' method in SQLConnectionManager class
- Revert "Fix tests for query comments." (commit a8309e92cb099b0245586a929059b71e3a731c1b)
- rename relation type 'materializedview' to 'materialized_view'
- adjust hooks tests
=> Update dbt-core to 1.6.0rc1

.changes/unreleased/Under the Hood-20230728-165543.yaml, dbt/include/trino/macros/materializations/materialized_view.sql, tests/functional/adapter/materialized_view_tests/test_materialized_view_dbt_core.py, tests/functional/adapter/materialized_view_tests/utils.py
- Adjusted materialized view macros to dbt-core implementation of materialized_view materialization
- Added new tests from dbt-tests-adapter
Our implementation of `materialized_view` materialization is removed, so [default implementation from dbt-core](https://github.com/dbt-labs/dbt-core/blob/v1.6.0rc1/core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql#L1) is used.
Adapter specific macros are implemented on our side.
Applying materialized view configuration changes via [ALTER SET PROPERTIES](https://trino.io/docs/current/sql/alter-materialized-view.html) is not supported.
Implementing that would require quite complex logic. I think that it could be added later, as currently Iceberg connector does not support setting materialized view …
=> Adjust materialized view macros

.changes/unreleased/Fixes-20230809-162435.yaml, dbt/adapters/trino/connections.py, tests/functional/adapter/show/fixtures.py, tests/functional/adapter/show/test_show.py
Implement missing `fetchmany` method in ConnectionWrapper.
Add tests for it.
=> Implement fetchmany

.changes/unreleased/Fixes-20230810-233738.yaml, dbt/include/trino/macros/adapters.sql, tests/functional/adapter/persist_docs/test_persist_docs.py
I accidentally changed default behavior in https://github.com/starburstdata/dbt-trino/pull/317
Resolves #343
Checked that it only sets the comment when:
```json
{{ config(
...
persist_docs={"relation": true}
) }}
```
And with the following configuration it won't set the comment:
```json
{{ config(
...
persist_docs={"relation": false}
) }}
```
```json
{{ config(
...
) }}
```
=> Only set the comment when persist_docs.relation is set

.changes/unreleased/Fixes-20230927-124454.yaml, dbt/include/trino/macros/adapters.sql
Before the change, the `list_relations_without_caching` macro queried `system.metadata.materialized_views` with no effective filter on the catalog and schema name. In theory the Trino optimizer could figure out the effective predicate on the `system.metadata.materialized_views` table, but in practice it was not happening, and all materialized views from all catalogs where being pulled.
=> Fix materialized_views filters when listing relations

.changes/unreleased/Under the Hood-20230929-211758.yaml, dbt/include/trino/macros/adapters.sql
`information_schema.schemata` has no duplicates.
=> Remove redundant `DISTINCT` from schema listing query

README.md, dev_requirements.txt
- Bump dbt-tests-adapter from 1.7.0rc1 to 1.7.0
- Expand 'Release process' section in README
=> Bump dbt-tests-adapter from 1.7.0rc1 to 1.7.0

.changes/unreleased/Under the Hood-20231003-161428.yaml, dbt/include/trino/macros/catalog.sql
`table_comments` is equally "hard" for the engine as `information_schema.columns`. Avoid optimizing the query on the `dbt` side by sending `UNION ALL` with individual schemas. Let the engine figure out the optimal strategy.
=> Query table_comments without unrolling with UNION ALL

.changes/unreleased/Under the Hood-20231206-171742.yaml, dbt/include/trino/macros/materializations/snapshot.sql, tests/functional/adapter/materialization/test_snapshot.py
Raise explicit error if location property is specified for snapshot
=> Raise explicit error if location property is specified for snapshot

.changes/unreleased/Dependencies-20240507-142214.yaml, .changes/unreleased/Dependencies-20240509-213722.yaml, .changes/unreleased/Fixes-20240506-130645.yaml, .github/workflows/bot-changelog.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/version-bump.yml, .pre-commit-config.yaml, dbt/adapters/trino/relation.py, dev_requirements.txt, setup.py, tests/functional/adapter/empty/test_empty.py
- Stop adding aliases to subqueries when calling with `--empty`
- add pre-commit check for dbt-core
- updated dependencies and GH actions
=> Stop adding aliases to render_limited output

.changes/unreleased/Fixes-20240729-101114.yaml, dbt/include/trino/macros/materializations/table.sql, docker/starburst/catalog/tpch.properties, docker/trino/catalog/tpch.properties, tests/functional/adapter/materialization/test_on_table_exists.py
Resolves https://github.com/starburstdata/dbt-trino/issues/423
=> Change table materialization logic when on_table_exists = 'rename'

.changes/unreleased/Features-20241015-174143.yaml, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/materializations/materialized_view.sql, tests/functional/adapter/test_table_properties.py
Add `file_format` and `table_format` configurations. This change aligns with the configurations that will be introduced in version 1.9 of the dbt-labs maintained adapters
=> Add file_format and table_format configurations

.changes/unreleased/Under the Hood-20241103-212520.yaml, dbt/adapters/trino/connections.py, tests/functional/adapter/test_insecure_warnings.py
=> Set SSL verification default to True

tests/functional/adapter/hooks/test_run_hooks.py
=> Fix test_run_hooks tests

.changes/unreleased/Fixes-20241126-125237.yaml, dbt/adapters/trino/impl.py, tests/functional/adapter/hooks/test_run_hooks.py
Resolves https://github.com/starburstdata/dbt-trino/issues/450
1.8.4 release broke compatibility with Python 3.8.
Keep Python 3.8 compatibility in dbt-trino 1.8.
Support for Python 3.8 will be dropped in dbt-trino 1.9 release.
=> Fix breaking compatibility with Python 3.8

.changes/unreleased/Features-20241211-095408.yaml, dbt/adapters/trino/connections.py, tests/unit/test_adapter.py
=> Allow users to suppress urllib3 warnings

.changes/unreleased/Under the Hood-20241105-083613.yaml, dbt/include/trino/macros/adapters.sql
We have noticed that queries against information_schema.columns are consistently faster than describe queries. Especially when using the glue catalog with an iceberg connector. For iceberg in particular, there has been particular optimizations made to speed up queries to information_schema.columns (this PR - https://github.com/trinodb/trino/pull/18315).
We've also seen this is faster for JDBC catalogs.
This PR is to query information_schema.columns for getting column information for a relation.
Resolves #443
=> Update trino__get_columns_in_relation to use information_schema.columns

.changes/unreleased/Features-20241202-132727.yaml, dbt/adapters/trino/impl.py, dbt/adapters/trino/relation.py, dbt/include/trino/macros/materializations/incremental.sql, tests/functional/adapter/materialization/test_incremental_microbatch.py
Add microbatch incremental strategy.
background:
https://github.com/dbt-labs/dbt-core/discussions/10672
This will be released in dbt-trino 1.9
=> Add microbatch incremental strategy

.changes/unreleased/Breaking Changes-20241024-172250.yaml, .changes/unreleased/Under the Hood-20241024-172431.yaml, .github/workflows/ci.yml, CONTRIBUTING.md, setup.py
=> Drop support for Python 3.8, add tests for Python 3.13

.changes/unreleased/Fixes-20250325-161315.yaml, .pre-commit-config.yaml, dbt/adapters/trino/column.py, tests/functional/adapter/column_types/fixtures.py, tests/functional/adapter/test_concurrency.py, tests/functional/adapter/unit_testing/test_unit_testing.py
resolves #437
VARBINARY and JSON should not be treated as string types.
No other dbt adapter does this.
=> Avoid treating VARBINARY and JSON as a string types

.changes/unreleased/Dependencies-20250528-191726.yaml, setup.py, tests/unit/test_adapter.py
Fix test for default query comment append behaviour, as default behaviour was changed in dbt-adapters 1.15.
Pin minor version of dbt-adapters, as minor updates may introduce breaking changes.
=> Fix test for default query comment append behaviour

.changes/unreleased/Features-20250602-212247.yaml, dbt/include/trino/macros/adapters.sql, dbt/include/trino/macros/materializations/table.sql, tests/functional/adapter/materialization/test_on_table_exists.py
implements on_table_exists=skip option
~~instead of creating the table, it simply executes "select 1"~~
resolves #479 
As requested by @damian3031 in [his feedback](https://github.com/starburstdata/dbt-trino/pull/481#pullrequestreview-2888519674), a revised checklist:
=> #479: on_table_exists=skip option for table materialization

.changes/unreleased/Fixes-20250617-195259.yaml, dbt/include/trino/macros/adapters.sql, tests/functional/adapter/materialization/fixtures.py, tests/functional/adapter/materialization/test_incremental_schema.py
When adding or removing columns from an incremental DBT Trino model, if the columns added/removed require quoting, the resulting SQL statement will throw a syntax error. This is because the macro `trino__alter_relation_add_remove_columns` does not wrap column names in double-quotes, like other macros do. This PR fixes that by wrapping column names with `adapter.quote()`. This functionality is already used in `trino__alter_column_type`, for example.
This PR also adds tests for this functionality. These tests also serve to test general `add_remove_columns` behavior, which today is untested as far as I can tell.
Resolves #491
=> Quote column names in `add_remove_columns` macro

.changes/unreleased/Dependencies-20250710-163129.yaml, setup.py
resolves: #493 
This should be relatively safe as I believe dbt-trino is compatible with dbt-adapters==1.16
=> Loosen dbt-adapters pin to allow for 1.16
