starburstdata/dbt-trino

- README.md
- dbt/adapters/trino/connections.py
- dbt/adapters/trino/impl.py
- test/unit/test_adapter.py
Addresses: https://github.com/findinpath/dbt-trino/issues/4
> Setting session properties

- README.md
- dbt/adapters/trino/connections.py
Improve `README.md` and add `dbt-trino` as a source in connection to `trino-python-client`
> Improve readme

- .github/workflows/release.yml
- README.md
ref: https://github.com/dbt-labs/dbt-presto/blob/master/.github/workflows/release.yml
> Add release pipeline

- .bumpversion-dbt.cfg
- .bumpversion.cfg
- README.md
- dbt/adapters/trino/__version__.py
- dbt/adapters/trino/connections.py
- dbt/adapters/trino/impl.py
- dbt/include/trino/__init__.py
- dev_requirements.txt
- docker-compose-starburst.yml
- docker-compose-trino.yml
- docker/dbt/Dockerfile
- docker/dbt/jaffle_shop/dbt_project.yml
- requirements.txt
- setup.py
- test/unit/utils.py
Upgrade dbt-trino to dbt-core v1.0.0.
Note: dbt-labs has not released official docker image yet.
> Upgrade to v1.0.0

- .github/pull_request_template.md
- .github/workflows/release.yml
- CHANGELOG.md
Introduce PR template and CHANGELOG.md for better maintenance and keep track of all changes in the project.
> Introduce PR template and CHANGELOG.md

- .bumpversion-dbt.cfg
- .bumpversion.cfg
- README.md
- dbt/adapters/trino/__version__.py
- docker-compose-starburst.yml
- docker-compose-trino.yml
- docker/starburst/etc/config.properties
- docker/trino/etc/config.properties
- requirements.txt
- setup.py
Release 1.0.3
- Description: Release 1.0.3
> Release 1.0.3

- CHANGELOG.md
- README.md
- dbt/include/trino/macros/materializations/table.sql
- docker/dbt/jaffle_shop/dbt_project.yml
- docker/dbt/jaffle_shop/models/table_drop/drop_customer_orders.sql
- docker/dbt/jaffle_shop/models/table_drop/schema.yml
- Description: Add support for on_table_exists in table materialization
- Related issue(s): https://github.com/starburstdata/dbt-trino/issues/26
> Add support for on_table_exists in table materialization

- README.md
- docker-compose-starburst.yml
- docker-compose-trino.yml
Use latest Trino & Starburst images to test dbt-trino functionality.
> Bump image requirements

- CHANGELOG.md
- dbt/adapters/trino/connections.py
Fixes #73 
- Description:
- Related issue(s): #73 
> Support user on jwt, certificate and OAuth authentication

- .bumpversion-dbt.cfg
- .bumpversion.cfg
- README.md
- dbt/adapters/trino/__version__.py
- docker-compose-starburst.yml
- docker-compose-trino.yml
- requirements.txt
- setup.py
> Release 1.1.1

- .bumpversion-dbt.cfg
- .bumpversion.cfg
- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- dbt/adapters/trino/__version__.py
- dbt/adapters/trino/column.py
- dbt/adapters/trino/connections.py
- dbt/include/trino/macros/adapters.sql
- dbt/include/trino/macros/crossdb/any_value.sql
- dbt/include/trino/macros/crossdb/bool_or.sql
- dbt/include/trino/macros/crossdb/current_timestamp.sql
- dbt/include/trino/macros/crossdb/datatypes.sql
- dbt/include/trino/macros/crossdb/date_trunc.sql
- dbt/include/trino/macros/crossdb/dateadd.sql
- dbt/include/trino/macros/crossdb/datediff.sql
- dbt/include/trino/macros/crossdb/hash.sql
- dbt/include/trino/macros/crossdb/listagg.sql
- dbt/include/trino/macros/crossdb/right.sql
- dbt/include/trino/macros/crossdb/safe_cast.sql
- docker/dbt/Dockerfile
- requirements.txt
- setup.py
- tests/functional/adapter/fixture_datediff.py
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/test_utils.py
- tests/unit/test_adapter.py
Implement dbt 1.2 features (except grants and tests for docs generation)
- Description:
- Related issue(s): #80 
> Upgrade to support dbt-core v1.2.0

- docker-compose-starburst.yml
- docker-compose-trino.yml
- Description: Bump Trino and Starburst versions
> Bump Trino and Starburst versions

- dbt/include/trino/macros/crossdb/any_value.sql
- dbt/include/trino/macros/crossdb/bool_or.sql
> Fix namespace of macros

- dbt/include/trino/macros/crossdb/datediff.sql
Avoid exception during compilation
> Avoid exception during compliation

- CHANGELOG.md
> Post release v1.2.0

- .github/workflows/security.yml
- CHANGELOG.md
Support Veracode code scanning
> Support Veracode code scanning

- CHANGELOG.md
- README.md
- docker-compose-starburst.yml
- docker-compose-trino.yml
- docker/starburst/catalog/delta.properties
- docker/starburst/catalog/iceberg.properties
- docker/trino/catalog/delta.properties
- docker/trino/catalog/iceberg.properties
- pytest.ini
- tests/conftest.py
Support delta lake and iceberg in tests.
> Add Delta Lake and Iceberg testing support

- .changes/unreleased/Security-20220822-131016.yaml
- setup.py
> Require 6.0 pyyaml version

- .changes/unreleased/Features-20220819-115505.yaml
- README.md
- dbt/include/trino/macros/materializations/incremental.sql
- docker-compose-starburst.yml
- docker-compose-trino.yml
- tests/conftest.py
- tests/functional/adapter/materialization/test_incremental_merge.py
> Add `merge` materialization

- .github/workflows/release.yml
> Fix get dbt-version in release flow

- .changes/unreleased/Dependencies-20220901-044453.yaml
- .github/workflows/bot-changelog.yml
Removes the newline at ened of the changelog entry for dependabot dependency bumps.
> Fix Dependency changelog

- README.md
- docker-compose-starburst.yml
- tests/functional/adapter/materialization/test_incremental_merge.py
> Enable merge strategy tests for Starburst

- .changes/unreleased/Under the Hood-20220826-162617.yaml
- dbt/include/trino/macros/catalog.sql
Add comments to catalog macro
Resolves #115
> Add comments to catalog macro

- .changes/unreleased/Features-20220901-155728.yaml
- CONTRIBUTING.md
- README.md
- dbt/adapters/trino/impl.py
- dbt/include/trino/macros/crossdb/current_timestamp.sql
- dbt/include/trino/macros/crossdb/datatypes.sql
- dbt/include/trino/macros/crossdb/date_trunc.sql
- dbt/include/trino/macros/crossdb/dateadd.sql
- dbt/include/trino/macros/crossdb/datediff.sql
- dbt/include/trino/macros/crossdb/safe_cast.sql
- dbt/include/trino/macros/materializations/snapshot.sql
- dbt/include/trino/macros/materializations/table.sql
- tests/functional/adapter/materialization/test_snapshot.py
- tests/functional/adapter/test_basic.py
> Implement `snapshot` materialization

- .changes/unreleased/Fixes-20220918-234135.yaml
- .changes/unreleased/Under the Hood-20220920-084055.yaml
- README.md
- dbt/adapters/trino/__init__.py
- dbt/adapters/trino/impl.py
- dbt/adapters/trino/relation.py
- tests/functional/adapter/test_quote_policy.py
> Add QuotePolicy for relations

- .changes/unreleased/Under the Hood-20220915-095940.yaml
- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- pytest.ini
- tests/conftest.py
- tests/functional/adapter/materialization/fixtures.py
- tests/functional/adapter/materialization/test_incremental_merge.py
- tests/functional/adapter/materialization/test_prepared_statements.py
- tests/functional/adapter/materialization/test_snapshot.py
- tests/functional/adapter/materialization/test_table_drop.py
- tests/functional/adapter/materialization/test_view_security.py
- tests/functional/adapter/persist_docs/test_persist_docs.py
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/test_utils.py
Add testing for Starburst Galaxy.
fixes #128
> Add testing for Starburst Galaxy

- tests/functional/adapter/test_basic.py
> Fix full-refresh test on Starburst Galaxy

- README.md
- docker-compose-starburst.yml
- docker-compose-trino.yml
- tests/functional/adapter/persist_docs/fixtures.py
- tests/functional/adapter/persist_docs/test_persist_docs.py
Fixes https://github.com/starburstdata/dbt-trino/issues/172
> Remove reference to limitation on Trino view column comments

- .changes/unreleased/Features-20221208-104815.yaml
- dbt/adapters/trino/connections.py
- tests/unit/test_adapter.py
resolves #111 
Added support for client_tags in profile configuration.
Unit tests added for this new config.
> Support client_tags in profile configuration

- .changes/unreleased/Under the Hood-20221215-121303.yaml
- dbt/include/trino/macros/materializations/table.sql
resolves #185 
Fix temp/backup identifier in table materialization
> Fix temp/backup identifier in table materialization

- .changes/unreleased/Fixes-20221215-184058.yaml
- .changes/unreleased/Fixes-20221219-135447.yaml
- dbt/include/trino/macros/materializations/incremental.sql
- tests/functional/adapter/test_get_incremental_tmp_relation_type_macro.py
resolves #195
Fix incremental materialization doesn't drop temp table.
Change views_enabled to true by default.
Add test for get_incremental_tmp_relation_type macro.
> Fix incremental materialization doesnt drop temp table

- .github/workflows/release.yml
> Bump Python version in release workflow

- README.md
> Add timezone to readme

- .changes/unreleased/Under the Hood-20230203-114039.yaml
- .github/workflows/ci.yml
- setup.py
resloves #225 
Added CI test for python 3.11
> Add support for Python 3.11

- .changes/unreleased/Under the Hood-20230224-130456.yaml
- requirements.txt
- setup.py
> Unpin dbt-core version

- docker-compose-starburst.yml
- docker-compose-trino.yml
- tests/functional/adapter/materialization/test_prepared_statements.py
> Small fixes

- .changes/unreleased/Breaking Changes-20230228-135914.yaml
- dbt/adapters/trino/column.py
Resolves second part of https://github.com/starburstdata/dbt-trino/issues/126 starting from https://github.com/starburstdata/dbt-trino/issues/126#issuecomment-1406649504
> Adapter methods return column types as is, except for decimal, varchar and char.

- Makefile
- dbt/adapters/trino/column.py
- tests/functional/adapter/test_seeds_column_types_overrides.py
- tests/functional/adapter/utils/test_timestamps.py
> Ensure test failures result in CI failure

- dbt/adapters/trino/connections.py
Add version in `source` connection parameter
> Add version in 'source' connection parameter

- .changes/unreleased/Features-20230304-002708.yaml
- dbt/include/trino/macros/adapters.sql
- tests/functional/adapter/materialization/test_materialized_view.py
> Support materialized view replacement

- dbt/adapters/trino/connections.py
- requirements.txt
- setup.py
Unpin trino python client minor version
> 1.1.latest Unpin trino python client minor version

- dbt/adapters/trino/connections.py
- setup.py
Unpin trino python client minor version
> 1.2.latest Unpin trino python client minor version

- dbt/adapters/trino/connections.py
- setup.py
Unpin trino python client minor version
> 1.3.latest Unpin trino python client minor version

- README.md
- docker-compose-starburst.yml
- docker-compose-trino.yml
> Upgrade Trino and SEP version

- .changes/unreleased/Under the Hood-20230424-163631.yaml
- .changes/unreleased/Under the Hood-20230424-163815.yaml
- dbt/adapters/trino/column.py
- tests/functional/adapter/column_types/fixtures.py
- tests/functional/adapter/column_types/test_column_types.py
- tests/functional/adapter/hooks/data/seed_model.sql
- tests/functional/adapter/hooks/data/seed_run.sql
- tests/functional/adapter/hooks/test_model_hooks.py
- tests/functional/adapter/hooks/test_run_hooks.py
- tests/functional/adapter/persist_docs/test_persist_docs.py
- tests/functional/adapter/test_caching.py
- tests/functional/adapter/test_simple_copy.py
- tests/functional/adapter/test_simple_snapshot.py
Add new tests from dbt-tests-adapter 1.5 to master
> Add new tests from dbt-tests-adapter 1.5 to master

- README.md
- docker-compose-starburst.yml
- docker-compose-trino.yml
Upgrade Trino to 414, SEP to 413-e
> Upgrade Trino to 414, SEP to 413-e

- tests/functional/adapter/hooks/test_run_hooks.py
- tests/functional/adapter/persist_docs/test_persist_docs.py
Fixes wrong assertions in hooks test.
> Fix hooks test assertions

- README.md
Fixed images paths to absolute, so it is properly rendered on PyPI
> Fix images paths to absolute, so it is properly rendered on PyPI

- dbt/include/trino/macros/catalog.sql
> List columns explicitly in catalog.sql

- .changes/unreleased/Features-20230607-111010.yaml
- dbt/adapters/trino/connections.py
- tests/functional/adapter/test_query_comments.py
- tests/unit/test_adapter.py
resolves https://github.com/starburstdata/dbt-trino/issues/305
- implemented query comments
- fixed bad tests from dbt-tests-adapter on our side. Could be reverted when tests will be fixed on dbt-core side.
> Implement query-comment

- .changes/unreleased/Under the Hood-20230619-154855.yaml
- tests/functional/adapter/hooks/test_hooks_delete.py
Resolves #307 
Test pre-hook & post-hook with DELETE statement
> Test pre-hook & post-hook with DELETE statement

- .changes/unreleased/Fixes-20230713-102021.yaml
- dbt/include/trino/macros/adapters.sql
- tests/functional/adapter/materialization/fixtures.py
- tests/functional/adapter/materialization/test_incremental_schema.py
> Fix sync_all_columns schema change strategy for incremental models

- README.md
- docker-compose-starburst.yml
- docker-compose-trino.yml
Upgrade Trino to 422, SEP to 420-e
> Upgrade Trino to 422,SEP to 420-e

- .changes/unreleased/Breaking Changes-20230718-130019.yaml
- CONTRIBUTING.md
- setup.py
Dropped support for Python 3.7
> Dropped support for Python 3.7

- .changes/unreleased/Under the Hood-20230728-180251.yaml
- .changes/unreleased/Under the Hood-20230801-125319.yaml
- tests/functional/adapter/constraints/fixtures.py
- tests/functional/adapter/constraints/test_constraints.py
- tests/functional/adapter/dbt_clone/test_dbt_clone.py
- tests/functional/adapter/dbt_debug/test_dbt_debug.py
- tests/functional/adapter/materialization/test_materialized_view.py
- tests/functional/adapter/store_failures/test_store_failures.py
- tests/functional/adapter/test_custom_schema.py
- tests/functional/adapter/utils/test_utils.py
- Add new tests from dbt-tests-adapter
- Add schema teardown method where necessary
> Add new tests from dbt-tests-adapter

- tests/functional/adapter/test_simple_copy.py
Add relations cleanup in test_simple_copy
> Add relations cleanup in test_simple_copy

- .changes/unreleased/Dependencies-20231006-120431.yaml
- README.md
- dev_requirements.txt
- docker-compose-starburst.yml
- docker-compose-trino.yml
- update dependencies
- update trino and SEP versions
> Update dependencies before 1.6.2 release

- .changes/unreleased/Breaking Changes-20231013-160933.yaml
- dbt/adapters/trino/__version__.py
- dbt/adapters/trino/relation.py
- dbt/include/trino/macros/adapters.sql
- dev_requirements.txt
- tests/functional/adapter/constraints/test_constraints.py
- tests/unit/utils.py
> Update dbt-core to 1.7.0rc1

- .changes/unreleased/Fixes-20231020-112317.yaml
- dbt/include/trino/macros/materializations/materialized_view.sql
> fix starburstdata/dbt-trino#366

- .changes/0.0.0.md
- CHANGELOG.md
> Add 1.6 changelog

- .changes/unreleased/Features-20231201-103207.yaml
- dbt/adapters/trino/connections.py
- tests/unit/test_adapter.py
> Add oauth_console authentication type

- .changes/unreleased/Under the Hood-20240122-140131.yaml
- .github/workflows/ci.yml
- setup.py
> Add tests against Python 3.12

- .changes/unreleased/Dependencies-20240306-121120.yaml
- .changes/unreleased/Under the Hood-20240306-121631.yaml
- README.md
- dev_requirements.txt
- docker-compose-starburst.yml
- docker-compose-trino.yml
Bump dependencies, Trino and SEP versions
> Bump dependencies, Trino and SEP versions

- .changes/unreleased/Features-20240812-161625.yaml
- dbt/adapters/trino/connections.py
- tests/functional/adapter/test_sql_status_output.py
Add update_type and rowcount to dbt commands SQL status in CLI output
> Add update_type and rowcount to dbt commands SQL status in CLI output

- .github/workflows/release.yml
Change source distribution filename to comply with PEP 625
> Change source distribution filename to comply with PEP 625

- .github/workflows/release.yml
- Comply with PEP 625
- Provision publishing permissions to PyPI via OIDC
> Comply with PEP 625, OIDC
